### ISSUE TITLE
Fedora installation not working.

### ISSUE THREAD

**Issue by reesericci** [sezanzeb/key-mapper#171]
Every installation method I try it fails in one way or another. Here's the log output after launching with the setup.py installation method: 
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/keymapper/logger.py", line 143, in <module>
    VERSION = pkg_resources.require('key-mapper')[0].version
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'evdev' distribution was not found and is required by key-mapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/site-packages/keymapper/logger.py", line 101, in format
    debug = is_debug()
NameError: name 'is_debug' is not defined
Call stack:
  File "/usr/bin/key-mapper-control", line 31, in <module>
    from keymapper.logger import logger, update_verbosity, log_info
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/keymapper/logger.py", line 148, in <module>
    logger.info('Could not figure out the version')
Message: 'Could not figure out the version'
Arguments: ()
```

**Comment by sezanzeb** [comment]
I pushed a fix for `NameError: name 'is_debug' is not defined`

As for `The 'evdev' distribution was not found`, do you have evdev installed? https://python-evdev.readthedocs.io/en/latest/install.html

**Comment by reesericci** [comment]
yeah, I have evdev installed and now I just get could not figure out the version.

**Comment by sezanzeb** [comment]
the `'Could not figure out the version'` error should not prevent the app from running. Does it still not run? Did you pull the latest changes from the github master?

**Comment by reesericci** [comment]
is there any specific way to uninstall the software? I tried again and it is still not working

**Comment by reesericci** [comment]
i used setup.py

**Comment by sezanzeb** [comment]
**use at your own risk**:

```
sudo find /usr -iname "*key*mapper" -exec rm {} -r \;
sudo find /etc -iname "*key*mapper" -exec rm {} -r \;
```

I have done this in the past and it worked.

This is what I meant with ["It will be a pain to uninstall"](https://github.com/sezanzeb/key-mapper/issues/181#issuecomment-913773083)
